"""added tenant to devices

Revision ID: 06121bcfe601
Revises: 8e240c0f9c70
Create Date: 2024-08-23 12:23:57.372441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06121bcfe601'
down_revision: Union[str, None] = '8e240c0f9c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('tenant', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'tenant')
    # ### end Alembic commands ###
