"""mac to messages

Revision ID: 307e413f7ad0
Revises: d7f9bc8c3c66
Create Date: 2024-08-22 20:45:28.334158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '307e413f7ad0'
down_revision: Union[str, None] = 'd7f9bc8c3c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('device_mac', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'device_mac')
    # ### end Alembic commands ###
