"""Add firmware upgrade date

Revision ID: 360452a31fc8
Revises: 21e02f1db02b
Create Date: 2024-10-11 15:13:13.505364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '360452a31fc8'
down_revision: Union[str, None] = '21e02f1db02b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('last_firmware_upgrade', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'last_firmware_upgrade')
    # ### end Alembic commands ###
