"""updated devices table, new PK

Revision ID: 5905dddb9c41
Revises: eae0df7da2b7
Create Date: 2024-09-20 16:30:37.266299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5905dddb9c41'
down_revision: Union[str, None] = 'eae0df7da2b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'mac_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index('ix_devices_id', table_name='devices')
    op.drop_column('devices', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index('ix_devices_id', 'devices', ['id'], unique=False)
    op.alter_column('devices', 'mac_id',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
