"""updated devices table, added rssi

Revision ID: 65970c5203ff
Revises: 7101e6027ea7
Create Date: 2024-09-20 15:48:27.171102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65970c5203ff'
down_revision: Union[str, None] = '7101e6027ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('rssi', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'rssi')
    # ### end Alembic commands ###
