"""updated messages table

Revision ID: 7101e6027ea7
Revises: 06121bcfe601
Create Date: 2024-09-20 15:13:10.158066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7101e6027ea7'
down_revision: Union[str, None] = '06121bcfe601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_timestamp', sa.TIMESTAMP(), nullable=True))
    op.add_column('messages', sa.Column('value_type', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('value', sa.NUMERIC(), nullable=True))
    op.drop_column('messages', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('messages', 'value')
    op.drop_column('messages', 'value_type')
    op.drop_column('messages', 'message_timestamp')
    # ### end Alembic commands ###
