"""changed tenantId type

Revision ID: 8e240c0f9c70
Revises: 307e413f7ad0
Create Date: 2024-08-22 21:06:09.780502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e240c0f9c70'
down_revision: Union[str, None] = '307e413f7ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tenant', sa.Text(), nullable=True))
    op.drop_column('messages', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'tenant')
    # ### end Alembic commands ###
