"""add devices table

Revision ID: d0f7cd5c6d6e
Revises: 5f8f911a2585
Create Date: 2024-08-20 21:18:58.667634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0f7cd5c6d6e'
down_revision: Union[str, None] = '5f8f911a2585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
