"""add surname finaly

Revision ID: d7f9bc8c3c66
Revises: d3e5781b1a5a
Create Date: 2024-08-22 19:47:29.553273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f9bc8c3c66'
down_revision: Union[str, None] = 'd3e5781b1a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_index('messages_id_idx', table_name='messages')
    op.add_column('users', sa.Column('surname', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'surname')
    op.create_index('messages_id_idx', 'messages', ['id', 'timestamp'], unique=True)
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    # ### end Alembic commands ###
