"""modify devices table

Revision ID: d9d3aa0e1422
Revises: d0f7cd5c6d6e
Create Date: 2024-08-20 21:28:51.825654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d3aa0e1422'
down_revision: Union[str, None] = 'd0f7cd5c6d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
