"""updated devices table, unique mac

Revision ID: eae0df7da2b7
Revises: 65970c5203ff
Create Date: 2024-09-20 16:20:54.131496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae0df7da2b7'
down_revision: Union[str, None] = '65970c5203ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_devices_mac_id', table_name='devices')
    op.create_index(op.f('ix_devices_mac_id'), 'devices', ['mac_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_mac_id'), table_name='devices')
    op.create_index('ix_devices_mac_id', 'devices', ['mac_id'], unique=False)
    # ### end Alembic commands ###
