"""updated devices table, firmware version

Revision ID: ec2d410b8e6e
Revises: 5905dddb9c41
Create Date: 2024-09-21 09:37:10.194546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec2d410b8e6e'
down_revision: Union[str, None] = '5905dddb9c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('firmware_version', sa.NUMERIC(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'firmware_version')
    # ### end Alembic commands ###
