version: '3.9'

services:
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb-savvyiot
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/timescaledb
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"